// source: src/pb/sb.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
//  prettier-ignore-start

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.Strand', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Strand = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Strand, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Strand.displayName = 'proto.Strand';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Strand.prototype.toObject = function(opt_includeInstance) {
  return proto.Strand.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Strand} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Strand.toObject = function(includeInstance, msg) {
  var f, obj = {
    strandId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    startTime: (f = msg.getStartTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    endTime: (f = msg.getEndTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    seedingProbability: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    infectionProbabilityMapP: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    infectionProbabilityMapK: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
    infectionProbabilityMapL: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0),
    incubationPeriodHoursAlpha: jspb.Message.getFloatingPointFieldWithDefault(msg, 8, 0.0),
    incubationPeriodHoursBeta: jspb.Message.getFloatingPointFieldWithDefault(msg, 9, 0.0),
    infectiousPeriodHoursAlpha: jspb.Message.getFloatingPointFieldWithDefault(msg, 10, 0.0),
    infectiousPeriodHoursBeta: jspb.Message.getFloatingPointFieldWithDefault(msg, 11, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Strand}
 */
proto.Strand.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Strand;
  return proto.Strand.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Strand} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Strand}
 */
proto.Strand.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setStrandId(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setStartTime(value);
      break;
    case 3:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setEndTime(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setSeedingProbability(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setInfectionProbabilityMapP(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setInfectionProbabilityMapK(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setInfectionProbabilityMapL(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setIncubationPeriodHoursAlpha(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setIncubationPeriodHoursBeta(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setInfectiousPeriodHoursAlpha(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setInfectiousPeriodHoursBeta(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Strand.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Strand.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Strand} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Strand.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStrandId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getStartTime();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getEndTime();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getSeedingProbability();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getInfectionProbabilityMapP();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = message.getInfectionProbabilityMapK();
  if (f !== 0.0) {
    writer.writeDouble(
      6,
      f
    );
  }
  f = message.getInfectionProbabilityMapL();
  if (f !== 0.0) {
    writer.writeDouble(
      7,
      f
    );
  }
  f = message.getIncubationPeriodHoursAlpha();
  if (f !== 0.0) {
    writer.writeDouble(
      8,
      f
    );
  }
  f = message.getIncubationPeriodHoursBeta();
  if (f !== 0.0) {
    writer.writeDouble(
      9,
      f
    );
  }
  f = message.getInfectiousPeriodHoursAlpha();
  if (f !== 0.0) {
    writer.writeDouble(
      10,
      f
    );
  }
  f = message.getInfectiousPeriodHoursBeta();
  if (f !== 0.0) {
    writer.writeDouble(
      11,
      f
    );
  }
};


/**
 * optional int64 strand_id = 1;
 * @return {number}
 */
proto.Strand.prototype.getStrandId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Strand} returns this
 */
proto.Strand.prototype.setStrandId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional google.protobuf.Timestamp start_time = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.Strand.prototype.getStartTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.Strand} returns this
*/
proto.Strand.prototype.setStartTime = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Strand} returns this
 */
proto.Strand.prototype.clearStartTime = function() {
  return this.setStartTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Strand.prototype.hasStartTime = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Timestamp end_time = 3;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.Strand.prototype.getEndTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 3));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.Strand} returns this
*/
proto.Strand.prototype.setEndTime = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Strand} returns this
 */
proto.Strand.prototype.clearEndTime = function() {
  return this.setEndTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Strand.prototype.hasEndTime = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional double seeding_probability = 4;
 * @return {number}
 */
proto.Strand.prototype.getSeedingProbability = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.Strand} returns this
 */
proto.Strand.prototype.setSeedingProbability = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional double infection_probability_map_p = 5;
 * @return {number}
 */
proto.Strand.prototype.getInfectionProbabilityMapP = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.Strand} returns this
 */
proto.Strand.prototype.setInfectionProbabilityMapP = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional double infection_probability_map_k = 6;
 * @return {number}
 */
proto.Strand.prototype.getInfectionProbabilityMapK = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.Strand} returns this
 */
proto.Strand.prototype.setInfectionProbabilityMapK = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional double infection_probability_map_l = 7;
 * @return {number}
 */
proto.Strand.prototype.getInfectionProbabilityMapL = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.Strand} returns this
 */
proto.Strand.prototype.setInfectionProbabilityMapL = function(value) {
  return jspb.Message.setProto3FloatField(this, 7, value);
};


/**
 * optional double incubation_period_hours_alpha = 8;
 * @return {number}
 */
proto.Strand.prototype.getIncubationPeriodHoursAlpha = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 8, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.Strand} returns this
 */
proto.Strand.prototype.setIncubationPeriodHoursAlpha = function(value) {
  return jspb.Message.setProto3FloatField(this, 8, value);
};


/**
 * optional double incubation_period_hours_beta = 9;
 * @return {number}
 */
proto.Strand.prototype.getIncubationPeriodHoursBeta = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 9, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.Strand} returns this
 */
proto.Strand.prototype.setIncubationPeriodHoursBeta = function(value) {
  return jspb.Message.setProto3FloatField(this, 9, value);
};


/**
 * optional double infectious_period_hours_alpha = 10;
 * @return {number}
 */
proto.Strand.prototype.getInfectiousPeriodHoursAlpha = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 10, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.Strand} returns this
 */
proto.Strand.prototype.setInfectiousPeriodHoursAlpha = function(value) {
  return jspb.Message.setProto3FloatField(this, 10, value);
};


/**
 * optional double infectious_period_hours_beta = 11;
 * @return {number}
 */
proto.Strand.prototype.getInfectiousPeriodHoursBeta = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 11, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.Strand} returns this
 */
proto.Strand.prototype.setInfectiousPeriodHoursBeta = function(value) {
  return jspb.Message.setProto3FloatField(this, 11, value);
};


goog.object.extend(exports, proto);
